# Generated by Django 4.1.4 on 2023-02-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RateObj',
        ),
    ]
