# Generated by Django 4.1.4 on 2023-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_build_in_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Free', 'Free'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10, verbose_name='Тип подписки')),
                ('duration', models.IntegerField(verbose_name='Длительность подписки')),
                ('duration_desc', models.CharField(max_length=10, verbose_name='Строковое описание длительности (месяц, год)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость подписки')),
                ('cost_for_week', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость подписки в неделю')),
                ('build_in_discount', models.IntegerField(blank=True, null=True, verbose_name='Заложенная в тариф скидка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['cost'],
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
