# Generated by Django 4.1.4 on 2023-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_subscriptiontype_build_in_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='cost_for_week',
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='build_in_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Процент скидки'),
        ),
    ]
