# Generated by Django 4.1.4 on 2023-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_subscriptiontype_cost_for_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('customerEmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта указанная клиентом')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='Пользователь сервиса, покупающий подписку')),
            ],
        ),
        migrations.AlterField(
            model_name='successnotification',
            name='OutSum',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость подписки'),
        ),
    ]
