# Generated by Django 4.1.4 on 2023-03-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_order_alter_successnotification_outsum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerEmail',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userEmail',
            new_name='user_email',
        ),
    ]
