# Generated by Django 4.1.4 on 2023-03-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailPaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField(db_index=True, verbose_name='Номер отмененного заказа')),
                ('out_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость подписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время получения уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление об успешном платеже',
                'verbose_name_plural': 'Уведомления об успешных платежах (ROBOKASSA)',
            },
        ),
        migrations.CreateModel(
            name='SuccessPaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_id', models.IntegerField(db_index=True, verbose_name='Номер успешного заказа')),
                ('out_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость подписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время получения уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление об успешном платеже',
                'verbose_name_plural': 'Уведомления об успешных платежах (ROBOKASSA)',
            },
        ),
        migrations.DeleteModel(
            name='SuccessNotification',
        ),
    ]
