# Generated by Django 4.1.4 on 2023-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_failpaymentnotification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='type',
            field=models.CharField(choices=[('Test', 'Free'), ('Start', 'First'), ('Middle', 'Second'), ('Long', 'Third')], max_length=10, verbose_name='Тип подписки'),
        ),
    ]
