# Generated by Django 4.1.7 on 2023-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_subscriptiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='cost',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Стоимость подписки'),
        ),
    ]
