# Generated by Django 4.1.7 on 2023-04-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_subscriptiontype_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failpaymentnotification',
            name='out_sum',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Стоимость подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='cost',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Стоимость подписки'),
        ),
        migrations.AlterField(
            model_name='successpaymentnotification',
            name='out_sum',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Стоимость подписки'),
        ),
    ]
