# Generated by Django 4.1.4 on 2023-01-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_accepted_terms_of_offer_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='storage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость хранения'),
        ),
    ]
