# Generated by Django 4.1.4 on 2023-01-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_salereport_cost_paid_acceptance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbapikey',
            name='last_reports_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления списка отчётов'),
        ),
    ]
