# Generated by Django 4.1.4 on 2023-01-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_netcost_amount_alter_netcost_cost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleobject',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_sales', to='users.wbapikey', verbose_name='Апи ключ'),
        ),
    ]
