# Generated by Django 4.1.4 on 2023-01-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_saleobject_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleobject',
            name='api_key',
        ),
        migrations.AlterField(
            model_name='salereport',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_key_reports', to='users.wbapikey', verbose_name='Апи ключ'),
        ),
    ]
