# Generated by Django 4.1.4 on 2023-01-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_saleobject_api_key_alter_salereport_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Уникальные отчёты'),
            preserve_default=False,
        ),
    ]
