# Generated by Django 4.1.4 on 2023-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_salereport_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuniqueproduct',
            name='product_name',
            field=models.CharField(max_length=125, null=True, verbose_name='Наименование товара'),
        ),
    ]
