# Generated by Django 4.1.4 on 2023-01-22 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_clientuniqueproduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleobject',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_key_sales', to='users.wbapikey', verbose_name='Апи ключ'),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Владелец отчёта'),
        ),
    ]
