# Generated by Django 4.1.4 on 2023-01-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_saleobject_api_key_alter_salereport_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='api_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_key_reports', to='users.wbapikey', verbose_name='Апи ключ'),
            preserve_default=False,
        ),
    ]
