# Generated by Django 4.1.4 on 2023-01-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_salereport_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleobject',
            name='api_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api_key_sales', to='users.wbapikey', verbose_name='Апи ключ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salereport',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_key_reports', to='users.wbapikey', verbose_name='Апи ключ'),
        ),
    ]
