# Generated by Django 4.1.4 on 2023-01-24 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_saleobject_api_key_alter_salereport_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netcost',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Значение себестоимости'),
        ),
        migrations.AlterField(
            model_name='wbapikey',
            name='api_key',
            field=models.TextField(max_length=900, validators=[django.core.validators.RegexValidator('^[^а-яА-Я]*$', 'Символы кириллицы в API ключе недопустимы')], verbose_name='API ключ Wildberries'),
        ),
    ]
