# Generated by Django 4.1.4 on 2023-01-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_netcost_users_netco_cost_da_c63b7f_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='netcost',
            name='users_netco_cost_da_c63b7f_idx',
        ),
    ]
