# Generated by Django 4.1.4 on 2023-01-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_netcost_users_netco_cost_da_c63b7f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleobject',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год продажи'),
        ),
        migrations.AddField(
            model_name='salereport',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год отчёта'),
        ),
    ]
