# Generated by Django 4.1.4 on 2023-02-15 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_saleobject_sa_name_alter_saleobject_ts_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncorrectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizationreport_id', models.BigIntegerField(verbose_name='Номер отчёта')),
                ('date_from', models.DateTimeField(verbose_name='Дата начала отчетного периода')),
                ('date_to', models.DateTimeField(verbose_name='Дата конца отчетного периода')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_api_key_reports', to='users.wbapikey', verbose_name='Апи ключ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_reports', to=settings.AUTH_USER_MODEL, verbose_name='Владелец отчёта')),
            ],
            options={
                'verbose_name': 'Некорректный отчёт',
                'verbose_name_plural': 'Некорректные отчёты',
            },
        ),
    ]
