# Generated by Django 4.1.4 on 2023-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_incorrectreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbapikey',
            name='is_active_import',
            field=models.BooleanField(default=False, verbose_name='Происходит ли загрузка отчёта'),
        ),
    ]
