# Generated by Django 4.1.4 on 2023-03-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_wbapikey_is_active_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectreport',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_api_key_reports', to='users.wbapikey', verbose_name='Api ключ'),
        ),
        migrations.CreateModel(
            name='UnloadedReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizationreport_id', models.BigIntegerField(verbose_name='Номер отчёта')),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unloaded_reports', to='users.wbapikey', verbose_name='Api ключ')),
            ],
            options={
                'verbose_name': 'Некорректный отчёт',
                'verbose_name_plural': 'Некорректные отчёты',
            },
        ),
    ]
