# Generated by Django 4.1.4 on 2023-03-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_incorrectreport_api_key_unloadedreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetCostsExelExampleObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_costs_file', models.FileField(upload_to='net_costs_example')),
            ],
        ),
        migrations.AlterModelOptions(
            name='unloadedreports',
            options={'verbose_name': 'Недозагруженный отчёт', 'verbose_name_plural': 'Недозагруженные отчёты'},
        ),
    ]
