# Generated by Django 4.1.4 on 2023-03-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_netcostsexelexampleobj_alter_unloadedreports_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netcostsexelexampleobj',
            options={'verbose_name': 'Пример заполнения себестоимости в Excel', 'verbose_name_plural': 'Примеры заполнения себестоимости в Excel'},
        ),
        migrations.AlterField(
            model_name='clientuniqueproduct',
            name='nm_id',
            field=models.BigIntegerField(unique=True, verbose_name='Артикул'),
        ),
    ]
