# Generated by Django 4.1.4 on 2023-03-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_netcostsexelexampleobj_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetCostsExelExampleObj',
        ),
    ]
