# Generated by Django 4.1.4 on 2023-03-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscriptiontype_delete_subscription'),
        ('users', '0030_delete_netcostsexelexampleobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Оплачена ли подписка'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_from', models.DateTimeField(verbose_name='Дата оформления подписки')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Окончательная стоимость подписки')),
                ('subscribed_to', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(verbose_name='Активна ли подписка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.subscriptiontype', verbose_name='Тип подписки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('is_active', 'user',),
                                               name='unique_user_active_subscription_priority'),
        ),
        migrations.AddConstraint(
            model_name='userdiscount',
            constraint=models.UniqueConstraint(fields=('is_active', 'user',),
                                               name='unique_user_active_discount_priority'),
        ),
    ]
