# Generated by Django 4.1.4 on 2023-03-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_is_subscribed_usersubscription_userdiscount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdiscount',
            name='unique_user_active_discount_priority',
        ),
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='unique_user_active_subscription_priority',
        ),
        migrations.AddConstraint(
            model_name='userdiscount',
            constraint=models.UniqueConstraint(fields=('is_active', 'user'), name='unique_user_active_discount_priority'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('is_active', 'user'), name='unique_user_active_subscription_priority'),
        ),
    ]
