# Generated by Django 4.1.4 on 2023-03-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_userdiscount_unique_user_active_discount_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdiscount',
            options={'verbose_name': 'Скидка пользователя', 'verbose_name_plural': 'Скидки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Подписка пользователя', 'verbose_name_plural': 'Подписки пользователей'},
        ),
    ]
