# Generated by Django 4.1.4 on 2023-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_order_customer_email_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleobject',
            name='acquiring_bank',
            field=models.CharField(max_length=40, null=True, verbose_name='Наименование банка, предоставляющего услуги эквайринга'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='acquiring_fee',
            field=models.FloatField(null=True, verbose_name='Возмещение расходов по эквайрингу'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='bonus_type_name',
            field=models.TextField(null=True, verbose_name='Обоснование штрафов и доплат'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='commission_percent',
            field=models.FloatField(null=True, verbose_name='Процент комиссии'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='declaration_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер таможенной декларации'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='delivery_amount',
            field=models.IntegerField(null=True, verbose_name='Количество доставок'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='gi_box_type_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Тип коробов'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='kiz',
            field=models.TextField(null=True, verbose_name='Код маркировки'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_inn',
            field=models.CharField(max_length=50, null=True, verbose_name='ИНН партнера'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_kvw_prc',
            field=models.FloatField(null=True, verbose_name='Итоговый кВВ без НДС, %'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_kvw_prc_base',
            field=models.FloatField(null=True, verbose_name='Размер кВВ без НДС, % базовый'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_office_id',
            field=models.IntegerField(null=True, verbose_name='Номер офиса'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_office_name',
            field=models.CharField(max_length=40, null=True, verbose_name='Наименование офиса доставки'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_reward',
            field=models.FloatField(null=True, verbose_name='Возмещение за выдачу и возврат товаров на ПВЗ'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_sales_commission',
            field=models.FloatField(null=True, verbose_name='Вознаграждение с продаж до вычета услуг поверенного, без НДС'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_spp_prc',
            field=models.FloatField(null=True, verbose_name='Скидка постоянного покупателя'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_supplier_id',
            field=models.BigIntegerField(null=True, verbose_name='Номер партнера'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_supplier_name',
            field=models.CharField(max_length=125, null=True, verbose_name='Партнёр'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_vw',
            field=models.FloatField(null=True, verbose_name='Вознаграждение WB без НДС'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='ppvz_vw_nds',
            field=models.FloatField(null=True, verbose_name='НДС с вознаграждения WB'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='product_discount_for_report',
            field=models.FloatField(null=True, verbose_name='Согласованный продуктовый дисконт'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='retail_amount',
            field=models.FloatField(default=1, verbose_name='Сумма продаж (возвратов)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleobject',
            name='return_amount',
            field=models.IntegerField(null=True, verbose_name='Количество возвратов'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='rr_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата операции'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='rrd_id',
            field=models.BigIntegerField(null=True, verbose_name='Номер строки'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='sale_percent',
            field=models.IntegerField(null=True, verbose_name='Согласованная скидка'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='shk_id',
            field=models.BigIntegerField(null=True, verbose_name='Штрих-код'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='sticker_id',
            field=models.CharField(max_length=40, null=True, verbose_name='Цифровое значение стикера'),
        ),
        migrations.AddField(
            model_name='saleobject',
            name='supplier_promo',
            field=models.FloatField(null=True, verbose_name='Промокод'),
        ),
    ]
