# Generated by Django 4.1.4 on 2023-03-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_saleobject_acquiring_bank_saleobject_acquiring_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleobject',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='users.clientuniqueproduct', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
