# Generated by Django 4.1.4 on 2023-03-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_saleobject_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleobject',
            name='product',
        ),
    ]
