# Generated by Django 4.1.4 on 2023-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_saleobject_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together=set(),
        ),
    ]
