# Generated by Django 4.1.4 on 2023-03-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_saleobject_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleobject',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='users.clientuniqueproduct', verbose_name='Товар'),
        ),
    ]
