# Generated by Django 4.1.4 on 2023-03-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_saleobject_product'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together={('year', 'week_num')},
        ),
    ]
