# Generated by Django 4.1.4 on 2023-03-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_saleobject_index_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Статус покупки подписки', 'verbose_name_plural': 'Статусы покупки подписки'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='processed', max_length=255, null=True),
        ),
    ]
