# Generated by Django 4.1.4 on 2023-03-23 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_remove_userdiscount_unique_user_active_discount_priority_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='unique_user_active_subscription_priority',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
    ]
