# Generated by Django 4.1.4 on 2023-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_remove_usersubscription_unique_user_active_subscription_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания ключа'),
        ),
    ]
