# Generated by Django 4.1.7 on 2023-04-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_wbapikey_created_at'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together={('brand_name', 'nm_id', 'product'), ('year', 'week_num')},
        ),
    ]
