# Generated by Django 4.1.7 on 2023-04-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_order_paid_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_sum',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_cost',
            field=models.DecimalField(decimal_places=7, max_digits=13, verbose_name='Окончательная стоимость подписки'),
        ),
    ]
