# Generated by Django 4.1.7 on 2023-04-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_saleobject_index_together'),
        ('users', '0052_alter_order_paid_sum_and_more'),
    ]

    operations = [
    ]
