# Generated by Django 4.1.7 on 2023-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_merge_20230416_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netcost',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Значение себестоимости'),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='cost_paid_acceptance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Стоимость платной приёмки'),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='other_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Прочие удержания'),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='storage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Стоимость хранения'),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='supplier_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Расходы поставщка'),
        ),
    ]
