# Generated by Django 4.1.7 on 2023-04-18 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_netcost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscount',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
