# Generated by Django 4.1.7 on 2023-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_userdiscount_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuniqueproduct',
            name='brand',
            field=models.CharField(default='Бренд отсутствует на WB', max_length=65, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='brand_name',
            field=models.CharField(default='Бренд отсутствует на WB', max_length=125, null=True, verbose_name='Бренд'),
        ),
    ]
