# Generated by Django 4.1.7 on 2023-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_alter_clientuniqueproduct_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuniqueproduct',
            name='brand',
            field=models.CharField(max_length=65, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='brand_name',
            field=models.CharField(max_length=125, null=True, verbose_name='Бренд'),
        ),
    ]
