# Generated by Django 4.1.7 on 2023-04-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_alter_clientuniqueproduct_brand_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together={('year', 'week_num'), ('brand_name', 'nm_id', 'barcode', 'product')},
        ),
    ]
