# Generated by Django 4.1.7 on 2023-04-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_saleobject_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together={('year', 'week_num'), ('barcode', 'product', 'nm_id')},
        ),
    ]
