# Generated by Django 4.1.7 on 2023-04-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_saleobject_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='clientuniqueproduct',
            index_together={('image', 'product_name')},
        ),
    ]
