# Generated by Django 4.1.7 on 2023-04-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_clientuniqueproduct_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='saleobject',
            index_together={('year', 'week_num'), ('barcode', 'nm_id')},
        ),
    ]
