# Generated by Django 4.1.7 on 2023-05-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_saleobject_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleobject',
            name='delivery_rub',
            field=models.FloatField(null=True, verbose_name='Стоимость логистики'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='order_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='retail_price_withdisc_rub',
            field=models.FloatField(null=True, verbose_name='Цена розничная с учетом согласованной скидки'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='sale_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='site_country',
            field=models.CharField(max_length=65, null=True, verbose_name='Страна продажи'),
        ),
        migrations.AlterField(
            model_name='saleobject',
            name='srid',
            field=models.CharField(max_length=225, null=True, verbose_name='Уникальный идентификатор заказа'),
        ),
    ]
