# Generated by Django 4.1.7 on 2023-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_alter_saleobject_rid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleobject',
            name='sale_percent',
            field=models.FloatField(null=True, verbose_name='Согласованная скидка'),
        ),
    ]
