# Generated by Django 4.2.5 on 2023-09-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_promocode_user_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.promocode', verbose_name='Промокод'),
        ),
    ]
