# Generated by Django 4.2.5 on 2023-11-02 21:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_promocode_discount_percent_alter_user_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrectreport',
            name='create_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования отчёта'),
        ),
        migrations.AddField(
            model_name='incorrectreport',
            name='week_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер недели'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='wbapikey',
            name='api_key',
            field=models.TextField(max_length=900, validators=[django.core.validators.RegexValidator('^[^а-яА-Я]*$', 'Символы кириллицы в API-ключе недопустимы')], verbose_name='API ключ Wildberries'),
        ),
    ]
