# Generated by Django 4.2.5 on 2023-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_alter_promocode_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='supplier_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Расходы поставщика'),
        ),
    ]
