# Generated by Django 4.2.5 on 2023-11-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_alter_promocode_owner_alter_saleobject_doc_type_name'),
        ('users', '0071_user_is_staff'),
    ]

    operations = [
    ]
