version: '3.9'

services:
  db:
    image: postgres:14.6
    container_name: commery_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: "dev"
    image: commery_docker:latest
    container_name: commery_django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/commery_project/static
      - media_volume:/commery_project/media
      - .:/commery_project
      - /var/web_logs:/commery_project/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:6.0.17
    container_name: commery_redis
  celery:
    build:
      dockerfile: Dockerfile
      context: .
      target: "dev"
    container_name: commery_celery
    command: celery -A config worker -l info
    volumes:
      - ./:/commery_project/commery_celery
      - /var/web_logs:/commery_project/logs
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data: