version: '3.9'

services:
  db:
    image: postgres:14.6
    container_name: commery_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: "prod"
    image: commery_docker:prod
    container_name: commery_django
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 config.wsgi:application"
    volumes:
      - static_volume:/commery_project/staticfiles
      - media_volume:/commery_project/media
      - .:/commery_project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:6.0.17
    container_name: commery_redis
  celery:
    build: .
    container_name: commery_celery
    command: celery -A config worker -l info
    volumes:
      - ./:/commery_project/commery_celery
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
      - nginx
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
    depends_on:
      - celery
  nginx:

    container_name: commery_nginx
    restart: unless-stopped
    image: nginx:1.23.3
    volumes:
      - static_volume:/commery_project/staticfiles
      - media_volume:/commery_project/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: commery_certbot
    restart: unless-stopped
    depends_on:
      - nginx
    environment:
      - DOMAIN=${DOMAIN_NAME}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
  postgres_data: