version: '3.9'

services:
  db:
    image: postgres:14.6
    container_name: commery_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
  pgbouncer:
    image: bitnami/pgbouncer:latest
    container_name: commery_pgbouncer
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - PGBOUNCER_DATABASE=${DB_NAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_HOST=${DB_HOST}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_PORT=${DB_PORT}
      - PGBOUNCER_POOL_MODE=${POOL_MODE}
      - PGBOUNCER_MAX_CLIENT_CONN=${MAX_CLIENT_CONN}
    depends_on:
      - db
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: "dev"
    image: commery_docker:latest
    container_name: commery_django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/commery_project/media
      - .:/commery_project
      - /var/web_logs:/commery_project/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:6.0.17
    container_name: commery_redis
  celery:
    build:
      dockerfile: Dockerfile
      context: .
      target: "dev"
    container_name: commery_celery
    command: celery -A config worker -l info
    volumes:
      - ./:/commery_project/commery_celery
      - /var/web_logs:/commery_project/logs
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
  celery-beat:
    build:
      dockerfile: Dockerfile
      context: .
      target: "dev"
    container_name: commery_celery_beat
    command: celery -A config beat -l info
    volumes:
      - ./:/commery_project/commery_celery
      - /var/web_logs:/commery_project/logs
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
  grafana:
    image: grafana/grafana:8.5.2
    container_name: commery_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - loki
      - prometheus
  promtail:
    image: grafana/promtail:2.5.0
    container_name: commery_promtail
    volumes:
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/web_logs:/var/log
    command: --config.file=/etc/promtail/promtail.yaml
    depends_on:
      - web
  loki:
    image: grafana/loki:2.5.0
    container_name: commery_loki
    ports:
      - "3100:3100"
    depends_on:
      - promtail
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: commery_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml

volumes:
  media_volume:
  postgres_data:
  grafana_data:
  prometheus_data: