global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: webapp-scraper
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'web:8000'
        labels:
          app: web

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

