# Generated by Django 4.1.4 on 2023-02-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Задать вопрос', 'Question'), ('Предложить идею', 'Idea'), ('Комментарий', 'Comment'), ('Сообщить об ошибке', 'Error')], max_length=18, verbose_name='Тип обращения')),
                ('user_name', models.CharField(max_length=65, verbose_name='Имя пользователя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение пользователя',
                'verbose_name_plural': 'Обращения пользователей',
            },
        ),
    ]
