# Generated by Django 4.1.4 on 2023-02-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_contactmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания обращения'),
        ),
    ]
