import pytest
import datetime


@pytest.fixture
def test_sale_objects_by_weeks():
    data = [
        {
            "year": 2022,
            "week_num": 48,
            "sales_sum": 152604.32999999946,
            "returns_sum": 1066.22,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 12.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 129432.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 680.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 223.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 143078.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 0.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 17169.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 0.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 52.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 122.0,
            "net_cost_storno_sale_sum": 0.0,
            "net_cost_correct_sale_sum": 0.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 22.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2022, 12, 4, 0, 30),
            "date_from": datetime.datetime(2022, 11, 28, 0, 30),
            "logistic_sum": 59786.050000000025,
            "penalty_sum": 140.0,
            "additional_payment_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 49,
            "sales_sum": 172604.32999999946,
            "returns_sum": 1066.22,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 122.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 129832.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 680.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 223.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 143078.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 57169.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 0.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 52.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 122.0,
            "net_cost_storno_sale_sum": 0.0,
            "net_cost_correct_sale_sum": 0.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2022, 12, 11, 0, 30),
            "date_from": datetime.datetime(2022, 12, 5, 0, 30),
            "logistic_sum": 38458.560000000005,
            "penalty_sum": 2160.0,
            "additional_payment_sum": 420.0,
        },
        {
            "year": 2022,
            "week_num": 50,
            "sales_sum": 172604.32999999946,
            "returns_sum": 1066.22,
            "storno_sales_sum": 55.2,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 41.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 122.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 129832.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 6810.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 223.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 183078.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 57169.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 0.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 52.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 122.0,
            "net_cost_storno_sale_sum": 0.0,
            "net_cost_correct_sale_sum": 0.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2022, 12, 18, 0, 30),
            "date_from": datetime.datetime(2022, 12, 12, 0, 30),
            "logistic_sum": 39039.21,
            "penalty_sum": 350.0,
            "additional_payment_sum": 1260.0,
        },
        {
            "year": 2022,
            "week_num": 51,
            "sales_sum": 172604.32999999946,
            "returns_sum": 1066.22,
            "storno_sales_sum": 55.2,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 41.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 122.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 129832.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 6810.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 223.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 183078.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 57169.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 0.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 1222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 11.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2022, 12, 25, 0, 30),
            "date_from": datetime.datetime(2022, 12, 19, 0, 30),
            "logistic_sum": 47432.36999999996,
            "penalty_sum": 18287.97,
            "additional_payment_sum": 1968.0,
        },
        {
            "year": 2022,
            "week_num": 52,
            "sales_sum": 172604.32999999946,
            "returns_sum": 106.22,
            "storno_sales_sum": 55.2,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 41.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 122.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 123832.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 6810.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 99.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 223.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 182078.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 61.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 51169.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 66.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 1222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 11.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2023, 1, 1, 0, 30),
            "date_from": datetime.datetime(2022, 12, 26, 0, 30),
            "logistic_sum": 279301.66000000015,
            "penalty_sum": 0.0,
            "additional_payment_sum": 510.0,
        },
        {
            "year": 2023,
            "week_num": 1,
            "sales_sum": 8813.97,
            "returns_sum": 106.22,
            "storno_sales_sum": 55.2,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 41.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 12.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 12832.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 680.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 9.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 23.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 18278.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 61.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 5119.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 66.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 11.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2023, 1, 8, 0, 30),
            "date_from": datetime.datetime(2023, 1, 2, 0, 30),
            "logistic_sum": 2429.9900000000002,
            "penalty_sum": 0.0,
            "additional_payment_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 2,
            "sales_sum": 337835.78999999905,
            "returns_sum": 5333.7300000000005,
            "storno_sales_sum": 55.2,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 41.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            'sales_payment_lost_marriage_sum': 12.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 1232.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 60.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 9.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 23.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 1878.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 61.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 5119.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 66.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 11.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 55.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 27.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2023, 1, 15, 0, 30),
            "date_from": datetime.datetime(2023, 1, 9, 0, 30),
            "logistic_sum": 287527.8800000011,
            "penalty_sum": 140.0,
            "additional_payment_sum": 426.0,
        },
        {
            "year": 2023,
            "week_num": 3,
            "sales_sum": 297708.49999999977,
            "returns_sum": 735.0799999999999,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 978.85,
            'sales_payment_lost_marriage_sum': 12.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 1232.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 902.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 60.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 9.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 23.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 18178.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 61.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 51219.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 66.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 111.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 552.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 217.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2023, 1, 22, 0, 30),
            "date_from": datetime.datetime(2023, 1, 16, 0, 30),
            "logistic_sum": 47578.80999999998,
            "penalty_sum": 10.0,
            "additional_payment_sum": 244.0,
        },
        {
            "year": 2023,
            "week_num": 4,
            "sales_sum": 334181.8800000007,
            "returns_sum": 2830.2799999999997,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 3439.5099999999998,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 281.82,
            'sales_payment_lost_marriage_sum': 12.2,
            'returns_payment_lost_marriage_sum': 10.10,
            "partial_compensation_marriage_sum": 0.0,
            'sales_advance_payment_goods_without_payment_sum': 11.0,
            'returns_advance_payment_goods_without_payment_sum': 12.5,
            "commission_sales_sum": 1232.51000000023,
            "commission_storno_sales_sum": 0.0,
            "commission_correct_sales_sum": 0.0,
            "commission_returns_sum": 9102.51,
            "commission_storno_returns_sum": 0.0,
            "commission_correct_returns_sum": 0.0,
            "commission_marriage_payment_sum": 0.0,
            'commission_sales_payment_lost_marriage_sum': 223.0,
            'commission_returns_payment_lost_marriage_sum': 11.0,
            "commission_partial_compensation_marriage_sum": 0.0,
            'commission_sales_advance_payment_goods_without_payment_sum': 23.0,
            'commission_returns_advance_payment_goods_without_payment_sum': 11.0,
            "sales_quantity_sum": 60.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 4.0,
            "strono_returns_quantity_sum": 9.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            'sales_payment_lost_marriage_quantity_sum': 23.0,
            'returns_payment_lost_marriage_quantity_sum': 11.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            'sales_advance_payment_goods_without_payment_quantity_sum': 12.0,
            'returns_advance_payment_goods_without_payment_quantity_sum': 11.0,
            "retail_sales_sum": 1818.01999999993,
            "retail_return_sum": 1043.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 112.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 61.0,
            "retail_marriage_payment_sum": 0.0,
            'retail_sales_payment_lost_marriage_sum': 2223.0,
            'retail_returns_payment_lost_marriage_sum': 500.0,
            'retail_partial_compensation_marriage_sum': 122.0,
            'retail_sales_advance_payment_goods_without_payment_sum': 111.0,
            'retail_returns_advance_payment_goods_without_payment_sum': 231.0,
            "tax_sale_sum": 1219.362399999987,
            "tax_storno_sale_sum": 0.0,
            "tax_correct_sale_sum": 66.0,
            "tax_return_sum": 125.16,
            "tax_storno_return_sum": 0.0,
            "tax_correct_return_sum": 0.0,
            "tax_marriage_payment_sum": 0.0,
            'tax_sales_payment_lost_marriage_sum': 532.0,
            'tax_returns_payment_lost_marriage_sum': 32.0,
            "tax_cost_partial_compensation_marriage_sum": 0.0,
            'tax_cost_sales_advance_payment_goods_without_payment_sum': 11.0,
            'tax_cost_returns_advance_payment_goods_without_payment_sum': 233.0,
            "net_cost_sale_sum": 222.0,
            "net_cost_storno_sale_sum": 52.0,
            "net_cost_correct_sale_sum": 11.0,
            "net_cost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 552.0,
            "net_cost_correct_return_sum": 51.1,
            "net_cost_marriage_payment_sum": 0.0,
            'net_cost_sales_payment_lost_marriage_sum': 217.0,
            'net_cost_returns_payment_lost_marriage_sum': 52.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            'net_cost_sales_advance_payment_goods_without_payment_sum': 22.0,
            'net_cost_returns_advance_payment_goods_without_payment_sum': 112.0,
            "date_to": datetime.datetime(2023, 1, 29, 0, 30),
            "date_from": datetime.datetime(2023, 1, 23, 0, 30),
            "logistic_sum": 67440.23000000007,
            "penalty_sum": 10.0,
            "additional_payment_sum": 464.0,
        },
    ]

    return data


@pytest.fixture
def test_sale_objects_by_products():
    data = [
        {
            "nm_id": 51897113,
            "sales_sum": 29814.39000000002,
            "returns_sum": 0.0,
            "storno_sales_sum": 1364.85,
            "correct_sales_sum": 1364.85,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            "payment_lost_marriage_sum": 0.0,
            "partial_compensation_marriage_sum": 0.0,
            "advance_payment_goods_without_payment_sum": 0.0,
            "сommission_sales_sum": 24022.76,
            "сommission_storno_sales_sum": 1160.12,
            "сommission_correct_sales_sum": 1094.57,
            "сommission_returns_sum": 0.0,
            "сommission_storno_returns_sum": 0.0,
            "сommission_correct_returns_sum": 0.0,
            "сommission_marriage_payment_sum": 0.0,
            "сommission_payment_lost_marriage_sum": 0.0,
            "сommission_partial_compensation_marriage_sum": 0.0,
            "сommission_advance_payment_goods_without_payment_sum": 0.0,
            "sales_quantity_sum": 33.0,
            "strono_sales_quantity_sum": 1.0,
            "correct_sales_quantity_sum": 1.0,
            "returns_quantity_sum": 0.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            "payment_lost_marriage_quantity_sum": 0.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            "advance_payment_goods_without_payment_quantity_sum": 0.0,
            "retail_sales_sum": 22320.0,
            "retail_return_sum": 0.0,
            "retail_storno_sales_sum": 969.0,
            "retail_correct_sales_sum": 969.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            "retail_payment_lost_marriage_sum": 0.0,
            "retail_partial_compensation_marriage_sum": 0.0,
            "retail_advance_payment_goods_without_payment_sum": 0.0,
            "netcost_sale_sum": 4026.0,
            "netcost_storno_sale_sum": 122.0,
            "netcost_correct_sale_sum": 122.0,
            "netcost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            "net_cost_payment_lost_marriage_sum": 0.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            "net_cost_advance_payment_goods_without_payment_sum": 0.0,
            "image": "https://basket-04.wb.ru/vol518/part51897/51897113/images/tm/1.jpg",
            "logistic_sum": 1978.0,
            "penalty_sum": 111.52,
            "additional_payment_sum": 0.0,
        },
        {
            "nm_id": 51897115,
            "sales_sum": 4481.1,
            "returns_sum": 0.0,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            "payment_lost_marriage_sum": 0.0,
            "partial_compensation_marriage_sum": 0.0,
            "advance_payment_goods_without_payment_sum": 0.0,
            "сommission_sales_sum": 3634.5,
            "сommission_storno_sales_sum": 0.0,
            "сommission_correct_sales_sum": 0.0,
            "сommission_returns_sum": 0.0,
            "сommission_storno_returns_sum": 0.0,
            "сommission_correct_returns_sum": 0.0,
            "сommission_marriage_payment_sum": 0.0,
            "сommission_payment_lost_marriage_sum": 0.0,
            "сommission_partial_compensation_marriage_sum": 0.0,
            "сommission_advance_payment_goods_without_payment_sum": 0.0,
            "sales_quantity_sum": 11.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 0.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            "payment_lost_marriage_quantity_sum": 0.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            "advance_payment_goods_without_payment_quantity_sum": 0.0,
            "retail_sales_sum": 3670.13,
            "retail_return_sum": 0.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 0.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            "retail_payment_lost_marriage_sum": 0.0,
            "retail_partial_compensation_marriage_sum": 0.0,
            "retail_advance_payment_goods_without_payment_sum": 0.0,
            "netcost_sale_sum": 2552.0,
            "netcost_storno_sale_sum": 0.0,
            "netcost_correct_sale_sum": 0.0,
            "netcost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            "net_cost_payment_lost_marriage_sum": 0.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            "net_cost_advance_payment_goods_without_payment_sum": 0.0,
            "image": "https://basket-04.wb.ru/vol518/part51897/51897115/images/tm/1.jpg",
            "logistic_sum": 410.0,
            "penalty_sum": 27.88,
            "additional_payment_sum": 0.0,
        },
        {
            "nm_id": 51897116,
            "sales_sum": 1614.6,
            "returns_sum": 0.0,
            "storno_sales_sum": 0.0,
            "correct_sales_sum": 0.0,
            "storno_returns_sum": 0.0,
            "correct_returns_sum": 0.0,
            "marriage_payment_sum": 0.0,
            "payment_lost_marriage_sum": 0.0,
            "partial_compensation_marriage_sum": 0.0,
            "advance_payment_goods_without_payment_sum": 0.0,
            "сommission_sales_sum": 1293.49,
            "сommission_storno_sales_sum": 0.0,
            "сommission_correct_sales_sum": 0.0,
            "сommission_returns_sum": 0.0,
            "сommission_storno_returns_sum": 0.0,
            "сommission_correct_returns_sum": 0.0,
            "сommission_marriage_payment_sum": 0.0,
            "сommission_payment_lost_marriage_sum": 0.0,
            "сommission_partial_compensation_marriage_sum": 0.0,
            "сommission_advance_payment_goods_without_payment_sum": 0.0,
            "sales_quantity_sum": 4.0,
            "strono_sales_quantity_sum": 0.0,
            "correct_sales_quantity_sum": 0.0,
            "returns_quantity_sum": 0.0,
            "strono_returns_quantity_sum": 0.0,
            "correct_return_quantity_sum": 0.0,
            "marriage_payment_quantity_sum": 0.0,
            "payment_lost_marriage_quantity_sum": 0.0,
            "partial_compensation_marriage_quantity_sum": 0.0,
            "advance_payment_goods_without_payment_quantity_sum": 0.0,
            "retail_sales_sum": 1291.1,
            "retail_return_sum": 0.0,
            "retail_storno_sales_sum": 0.0,
            "retail_correct_sales_sum": 0.0,
            "retail_storno_returns_sum": 0.0,
            "retail_correct_returns_sum": 0.0,
            "retail_marriage_payment_sum": 0.0,
            "retail_payment_lost_marriage_sum": 0.0,
            "retail_partial_compensation_marriage_sum": 0.0,
            "retail_advance_payment_goods_without_payment_sum": 0.0,
            "netcost_sale_sum": 4888.0,
            "netcost_storno_sale_sum": 0.0,
            "netcost_correct_sale_sum": 0.0,
            "netcost_return_sum": 0.0,
            "net_cost_strono_returns_sum": 0.0,
            "net_cost_correct_return_sum": 0.0,
            "net_cost_marriage_payment_sum": 0.0,
            "net_cost_payment_lost_marriage_sum": 0.0,
            "net_cost_partial_compensation_marriage_sum": 0.0,
            "net_cost_advance_payment_goods_without_payment_sum": 0.0,
            "image": "https://basket-04.wb.ru/vol518/part51897/51897116/images/tm/1.jpg",
            "logistic_sum": 134.0,
            "penalty_sum": 0.0,
            "additional_payment_sum": 0.0,
        }
    ]

    return data


@pytest.fixture
def test_supplier_costs_sum_list():
    data = [
        {
            "year": 2022,
            "week_num": 48,
            "date_to": datetime.datetime(2022, 12, 4, 0, 30),
            "date_from": datetime.datetime(2022, 11, 28, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 49,
            "date_to": datetime.datetime(2022, 12, 11, 0, 30),
            "date_from": datetime.datetime(2022, 12, 5, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 50,
            "date_to": datetime.datetime(2022, 12, 18, 0, 30),
            "date_from": datetime.datetime(2022, 12, 12, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 51,
            "date_to": datetime.datetime(2022, 12, 25, 0, 30),
            "date_from": datetime.datetime(2022, 12, 19, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 52,
            "date_to": datetime.datetime(2023, 1, 1, 0, 30),
            "date_from": datetime.datetime(2022, 12, 26, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 1,
            "date_to": datetime.datetime(2023, 1, 8, 0, 30),
            "date_from": datetime.datetime(2023, 1, 2, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 2,
            "date_to": datetime.datetime(2023, 1, 15, 0, 30),
            "date_from": datetime.datetime(2023, 1, 9, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 3,
            "date_to": datetime.datetime(2023, 1, 22, 0, 30),
            "date_from": datetime.datetime(2023, 1, 16, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 4,
            "date_to": datetime.datetime(2023, 1, 29, 0, 30),
            "date_from": datetime.datetime(2023, 1, 23, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 5,
            "date_to": datetime.datetime(2023, 2, 5, 0, 30),
            "date_from": datetime.datetime(2023, 1, 30, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 6,
            "date_to": datetime.datetime(2023, 2, 12, 0, 30),
            "date_from": datetime.datetime(2023, 2, 6, 0, 30),
            "supplier_costs_sum": 1122.0,
        },
        {
            "year": 2023,
            "week_num": 7,
            "date_to": datetime.datetime(2023, 2, 19, 0, 30),
            "date_from": datetime.datetime(2023, 2, 13, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 8,
            "date_to": datetime.datetime(2023, 2, 26, 0, 30),
            "date_from": datetime.datetime(2023, 2, 20, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 9,
            "date_to": datetime.datetime(2023, 3, 5, 0, 30),
            "date_from": datetime.datetime(2023, 2, 27, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 10,
            "date_to": datetime.datetime(2023, 3, 12, 0, 30),
            "date_from": datetime.datetime(2023, 3, 6, 0, 30),
            "supplier_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 11,
            "date_to": datetime.datetime(2023, 3, 19, 0, 30),
            "date_from": datetime.datetime(2023, 3, 13, 0, 30),
            "supplier_costs_sum": 111.0,
        },
        {
            "year": 2023,
            "week_num": 12,
            "date_to": datetime.datetime(2023, 3, 26, 0, 30),
            "date_from": datetime.datetime(2023, 3, 20, 0, 30),
            "supplier_costs_sum": 121.0,
        },
    ]

    return data


@pytest.fixture
def test_wb_costs_sum_list():
    data = [
        {
            "year": 2022,
            "week_num": 48,
            "date_to": datetime.datetime(2022, 12, 4, 0, 30),
            "date_from": datetime.datetime(2022, 11, 28, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 49,
            "date_to": datetime.datetime(2022, 12, 11, 0, 30),
            "date_from": datetime.datetime(2022, 12, 5, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 50,
            "date_to": datetime.datetime(2022, 12, 18, 0, 30),
            "date_from": datetime.datetime(2022, 12, 12, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 51,
            "date_to": datetime.datetime(2022, 12, 25, 0, 30),
            "date_from": datetime.datetime(2022, 12, 19, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2022,
            "week_num": 52,
            "date_to": datetime.datetime(2023, 1, 1, 0, 30),
            "date_from": datetime.datetime(2022, 12, 26, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 1,
            "date_to": datetime.datetime(2023, 1, 8, 0, 30),
            "date_from": datetime.datetime(2023, 1, 2, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 2,
            "date_to": datetime.datetime(2023, 1, 15, 0, 30),
            "date_from": datetime.datetime(2023, 1, 9, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 3,
            "date_to": datetime.datetime(2023, 1, 22, 0, 30),
            "date_from": datetime.datetime(2023, 1, 16, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 4,
            "date_to": datetime.datetime(2023, 1, 29, 0, 30),
            "date_from": datetime.datetime(2023, 1, 23, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 5,
            "date_to": datetime.datetime(2023, 2, 5, 0, 30),
            "date_from": datetime.datetime(2023, 1, 30, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 6,
            "date_to": datetime.datetime(2023, 2, 12, 0, 30),
            "date_from": datetime.datetime(2023, 2, 6, 0, 30),
            "total_wb_costs_sum": 6798.0,
        },
        {
            "year": 2023,
            "week_num": 7,
            "date_to": datetime.datetime(2023, 2, 19, 0, 30),
            "date_from": datetime.datetime(2023, 2, 13, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 8,
            "date_to": datetime.datetime(2023, 2, 26, 0, 30),
            "date_from": datetime.datetime(2023, 2, 20, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 9,
            "date_to": datetime.datetime(2023, 3, 5, 0, 30),
            "date_from": datetime.datetime(2023, 2, 27, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 10,
            "date_to": datetime.datetime(2023, 3, 12, 0, 30),
            "date_from": datetime.datetime(2023, 3, 6, 0, 30),
            "total_wb_costs_sum": 0.0,
        },
        {
            "year": 2023,
            "week_num": 11,
            "date_to": datetime.datetime(2023, 3, 19, 0, 30),
            "date_from": datetime.datetime(2023, 3, 13, 0, 30),
            "total_wb_costs_sum": 122.0,
        },
        {
            "year": 2023,
            "week_num": 12,
            "date_to": datetime.datetime(2023, 3, 26, 0, 30),
            "date_from": datetime.datetime(2023, 3, 20, 0, 30),
            "total_wb_costs_sum": 2446.0,
        },
    ]

    return data


@pytest.fixture
def test_calculated_financials_by_products():
    financials_by_products = [
        {
            'nm_id': 143449349,
            'barcode': '2037382511266',
            'image': 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            'product_name': 'Женская футболка хлопковая с коротким рукавом реглан',
            'revenue_by_article': 2722.13,
            'share_in_revenue': 1.2742567674220782,
            'product_marginality': 0.0,
            'share_in_number': 2.127659574468085
        },
        {
            'nm_id': 143449349,
            'barcode': '2037382511273',
            'image': 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            'product_name': 'Женская футболка хлопковая с коротким рукавом реглан',
            'revenue_by_article': 2324.0,
            'share_in_revenue': 1.087888060999625,
            'product_marginality': 0.0,
            'share_in_number': 2.127659574468085},
        {
            'nm_id': 143449349,
            'barcode': '2037382511280',
            'image': 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            'product_name': 'Женская футболка хлопковая с коротким рукавом реглан',
            'revenue_by_article': 4950.44,
            'share_in_revenue': 2.31735136518717,
            'product_marginality': 0.0,
            'share_in_number': 2.127659574468085
        },
        {
            'nm_id': 143449349,
            'barcode': '2037382511297',
            'image': 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            'product_name': 'Женская футболка хлопковая с коротким рукавом реглан',
            'revenue_by_article': 2302.0,
            'share_in_revenue': 1.0775896370142586,
            'product_marginality': 0.0, 'share_in_number': 2.127659574468085},
        {
            'nm_id': 143449354,
            'barcode': '2037382511570',
            'image': 'https://basket-10.wb.ru/vol1434/part143449/143449354/images/tm/1.jpg',
            'product_name': 'Женская футболка хлопковая с коротким рукавом реглан',
            'revenue_by_article': 2807.88,
            'share_in_revenue': 1.3143972154559498,
            'product_marginality': 0.0,
            'share_in_number': 2.127659574468085
        }
    ]

    return financials_by_products


@pytest.fixture
def test_expected_calculated_abc_values():
    expected_calculated_abc_values = {
        'nm_id': {2: 143449349, 4: 143449354, 0: 143449349, 1: 143449349, 3: 143449349},
        'barcode': {2: '2037382511280', 4: '2037382511570', 0: '2037382511266', 1: '2037382511273', 3: '2037382511297'},
        'image': {
            2: 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            4: 'https://basket-10.wb.ru/vol1434/part143449/143449354/images/tm/1.jpg',
            0: 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            1: 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg',
            3: 'https://basket-10.wb.ru/vol1434/part143449/143449349/images/tm/1.jpg'},
        'product_name': {
            2: 'Женская футболка хлопковая с коротким рукавом реглан',
            4: 'Женская футболка хлопковая с коротким рукавом реглан',
            0: 'Женская футболка хлопковая с коротким рукавом реглан',
            1: 'Женская футболка хлопковая с коротким рукавом реглан',
            3: 'Женская футболка хлопковая с коротким рукавом реглан'},
        'revenue_by_article': {2: 4950.44, 4: 2807.88, 0: 2722.13, 1: 2324.0, 3: 2302.0},
        'share_in_revenue': {
            2: 2.31735136518717,
            4: 1.3143972154559498,
            0: 1.2742567674220782,
            1: 1.087888060999625,
            3: 1.0775896370142586
        },
        'product_marginality': {2: 0.0, 4: 0.0, 0: 0.0, 1: 0.0, 3: 0.0},
        'share_in_number': {
            2: 2.127659574468085,
            4: 2.127659574468085,
            0: 2.127659574468085,
            1: 2.127659574468085,
            3: 2.127659574468085
        },
        'increasing_proportion': {
            2: 2.31735136518717,
            4: 3.6317485806431202,
            0: 4.906005348065198,
            1: 5.993893409064824,
            3: 7.0714830460790825
        },
        'group_abc': {2: 'A', 4: 'A', 0: 'A', 1: 'A', 3: 'A'}
    }

    return expected_calculated_abc_values



