# Generated by Django 4.1.4 on 2023-01-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportByProductType',
        ),
    ]
