# Generated by Django 4.1.4 on 2023-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalinformationobj',
            options={'verbose_name': 'Сообщение для пользователей', 'verbose_name_plural': 'Сообщения для пользователей'},
        ),
        migrations.AddField(
            model_name='generalinformationobj',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
