# Generated by Django 4.1.4 on 2023-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_generalinformationobj_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generalinformationobj',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('info_type', 'is_active'), name='unique_is_active'),
        ),
    ]
